package client;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.*;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

//import static client.Auth.executeSql;


public class
User extends JFrame {
    private static String tableName = "user";
    private JTable jTable1;
    private String[][] data;

    public User() throws IOException {
        initComponents();

        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jButton1 = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        textLogin = new JTextField();
        textPass = new JTextField();
        jButton2 = new JButton();
        jButton3 = new JButton();

        setTitle("Пользователи");

        jTable1.setModel(new DefaultTableModel());
        jTable1.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jTable1.setAutoCreateRowSorter(true);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Добавить");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel1.setText("Логин");
        jLabel2.setText("Пароль");

        jButton2.setForeground(new Color(255, 51, 51));
        jButton2.setText("Удалить");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new Color(255, 153, 51));
        jButton3.setText("Изменить");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 527, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(textLogin, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textPass, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(textLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(textPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(ActionEvent evt) throws IOException {//GEN-FIRST:event_jButton1ActionPerformed
        String login = textLogin.getText();
        String pass = textPass.getText();

        if (login.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ошибка ввода!",
                    "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            if (isUserExistsByLogin(login)) {
                JOptionPane.showMessageDialog(null,
                        "Такой пользователь существует!",
                        "Ошибка",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                insertData(login, pass);
            }
        }

        textLogin.setText("");
        textPass.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowIndex = jTable1.getSelectedRow();
        String recordId = null;

        try {
            recordId = (String) jTable1.getValueAt(rowIndex, 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Ошибка выбора записи!",
                    "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        }
        recordId = data[rowIndex][0];
        deleteData(recordId);

        textLogin.setText("");
        textPass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int rowIndex = jTable1.getSelectedRow();
        String recordId = null;

        try {
            recordId = data[rowIndex][0];
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null,
                    "Ошибка выбора записи!",
                    "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        }

        String login = textLogin.getText();
        String pass = textPass.getText();

        if (login.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null,
                    "Ошибка ввода!",
                    "Ошибка",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            updateData(login, pass, recordId);
        }

        textLogin.setText("");
        textPass.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MousePressed(MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int rowIndex = jTable1.getSelectedRow();
        textLogin.setText((String) jTable1.getValueAt(rowIndex, 0));
        textPass.setText((String) jTable1.getValueAt(rowIndex, 1));
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalAccessException, UnsupportedLookAndFeelException, InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new User().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void refreshTable() throws IOException {
        Object[] column = {"Логин", "Пароль"};
       // String[][] data = getData();
        data = getData();
        String[][] data1 = new String[data.length][data[0].length - 1];
        for (int i = 0; i < data.length; i++) {
            for (int j = 0; j < data[i].length - 1; j++) {
                data1[i][j] = data[i][j + 1];
            }
        }

        DefaultTableModel model = new DefaultTableModel(data1, column);
        jTable1.setModel(model);
    }

    public String[][] getData() throws IOException {
        return getAll();
    }

    private static String[][] getAll() throws IOException {
        ObjectOutputStream out;
        String serverAddress = "127.0.0.1";
        Socket clientSocket = new Socket(serverAddress, 8080);

        try {
            out = new ObjectOutputStream(clientSocket.getOutputStream());
            out.writeObject("get@user@no_sql");

            ObjectInputStream input = new ObjectInputStream(clientSocket.getInputStream());

            return (String[][]) input.readObject();
        } catch (Exception e) {
           // System.out.println(e);
        }

        clientSocket.close();

        return null;
    }

    private void insertData(String login, String pass) {
        try {
            String sql = "INSERT INTO " + tableName + " (login, pass) VALUES ('" + login + "', '" + pass + "')";
            Auth.executeSql(sql, "insert");

            refreshTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean isUserExistsByLogin(String login) throws IOException {
        ObjectOutputStream out;
        String serverAddress = "127.0.0.1";
        Socket clientSocket = new Socket(serverAddress, 8080);

        String sql = " WHERE login = " + login;

        try {
            out = new ObjectOutputStream(clientSocket.getOutputStream());
            out.writeObject("get@user@" + sql);

            ObjectInputStream input = new ObjectInputStream(clientSocket.getInputStream());
            String[][] data = (String[][]) input.readObject();

            if (data.length > 0) {
                return true;
            }
        } catch (Exception e) {
           // System.out.println(e);
        }

        return false;
    }

    private void deleteData(String id) {
       /* try {
            String sql = "DELETE FROM " + tableName + " WHERE id = '" + id + "'";
            Auth.executeSql(sql, "delete");

            refreshTable();
        } catch (Exception e) {
            e.printStackTrace();
        }*/
        try {
            if (Integer.parseInt(id) == GlobalVariable.getUserId()) {
                JOptionPane.showMessageDialog(null,
                        "Ошибка удаления!",
                        "Ошибка",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                String sql = "DELETE FROM " + tableName + " WHERE id = '" + id + "'";
                Auth.executeSql(sql, "delete");
            }

            refreshTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateData(String login, String pass, String id) {
        try {
            String sql = "UPDATE " + tableName + " login SET login = '" + login + "', pass = '" + pass + "' WHERE id = '" + id + "'";
            Auth.executeSql(sql, "update");

            refreshTable();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JScrollPane jScrollPane1;
    private JTextField textLogin;
    private JTextField textPass;
    private JPanel panel2;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel2 = new JPanel();
        panel2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel2.setEnabled(true);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel2;
    }

    // End of variables declaration//GEN-END:variables
}